<a href="https://colab.research.google.com/github/rohit958/Coursera_repo/blob/main/PreprocessingImmigration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! pip install openpyxl==3.0.9

Collecting openpyxl==3.0.9
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.2/242.2 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl==3.0.9) (1.1.0)
Installing collected packages: openpyxl
  Attempting uninstall: openpyxl
    Found existing installation: openpyxl 3.1.3
    Uninstalling openpyxl-3.1.3:
      Successfully uninstalled openpyxl-3.1.3
Successfully installed openpyxl-3.0.9

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
df_can = pd.read_excel(
    'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.xlsx',
    sheet_name='Canada by Citizenship',
    skiprows=range(20),
    skipfooter=2)

print('Data read into a pandas dataframe!')

Data read into a pandas dataframe!

In [5]:
df_can.head()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [6]:
df_can.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 43 entries, Type to 2013
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

In [7]:
df_can.columns

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')

In [8]:
df_can.index

RangeIndex(start=0, stop=195, step=1)

In [9]:
print(type(df_can.columns))
print(type(df_can.index))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.range.RangeIndex'>

In [19]:
print(df_can.columns.tolist())

['Country', 'Continent', 'Region', 'DevName', 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 'Total']

In [20]:
print(df_can.index.tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194]

In [12]:
df_can.shape

(195, 43)

In [13]:
df_can.drop(['AREA','REG','DEV','Type','Coverage'], axis=1, inplace=True)
df_can.head(2)

,OdName,AreaName,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603

In [14]:
df_can.rename(columns={'OdName':'Country', 'AreaName':'Continent', 'RegName':'Region'}, inplace=True)
df_can.columns

Index([  'Country', 'Continent',    'Region',   'DevName',        1980,
              1981,        1982,        1983,        1984,        1985,
              1986,        1987,        1988,        1989,        1990,
              1991,        1992,        1993,        1994,        1995,
              1996,        1997,        1998,        1999,        2000,
              2001,        2002,        2003,        2004,        2005,
              2006,        2007,        2008,        2009,        2010,
              2011,        2012,        2013],
      dtype='object')

In [23]:
df_can.isnull().sum()

Country      0
Continent    0
Region       0
DevName      0
1980         0
1981         0
1982         0
1983         0
1984         0
1985         0
1986         0
1987         0
1988         0
1989         0
1990         0
1991         0
1992         0
1993         0
1994         0
1995         0
1996         0
1997         0
1998         0
1999         0
2000         0
2001         0
2002         0
2003         0
2004         0
2005         0
2006         0
2007         0
2008         0
2009         0
2010         0
2011         0
2012         0
2013         0
Total        0
dtype: int64

In [24]:
df_can.describe()

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,508.394872,566.989744,534.723077,387.435897,376.497436,358.861538,441.271795,691.133333,714.389744,843.241026,...,1320.292308,1266.958974,1191.820513,1246.394872,1275.733333,1420.287179,1262.533333,1313.958974,1320.702564,32867.451282
std,1949.588546,2152.643752,1866.997511,1204.333597,1198.246371,1079.309600,1225.576630,2109.205607,2443.606788,2555.048874,...,4425.957828,3926.717747,3443.542409,3694.573544,3829.630424,4462.946328,4030.084313,4247.555161,4237.951988,91785.498686
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,1.000000,1.000000,...,28.500000,25.000000,31.000000,31.000000,36.000000,40.500000,37.500000,42.500000,45.000000,952.000000
50%,13.000000,10.000000,11.000000,12.000000,13.000000,17.000000,18.000000,26.000000,34.000000,44.000000,...,210.000000,218.000000,198.000000,205.000000,214.000000,211.000000,179.000000,233.000000,213.000000,5018.000000
75%,251.500000,295.500000,275.000000,173.000000,181.000000,197.000000,254.000000,434.000000,409.000000,508.500000,...,832.000000,842.000000,899.000000,934.500000,888.000000,932.000000,772.000000,783.000000,796.000000,22239.500000
max,22045.000000,24796.000000,20620.000000,10015.000000,10170.000000,9564.000000,9470.000000,21337.000000,27359.000000,23795.000000,...,42584.000000,33848.000000,28742.000000,30037.000000,29622.000000,38617.000000,36765.000000,34315.000000,34129.000000,691904.000000

In [25]:
df_can.columns = list(map(str, df_can.columns))
# [print (type(x)) for x in df_can.columns.values] #<-- uncomment to check type of column headers

In [26]:
years = list(map(str, range(1980, 2014)))
years

['1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [27]:
year=list(map(str,range(1990,2013)))
year

['1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012']

In [28]:
condition = df_can['Continent'] == 'Asia'
print(condition)

0       True
1      False
2      False
3      False
4      False
       ...
190     True
191    False
192     True
193    False
194    False
Name: Continent, Length: 195, dtype: bool

In [29]:
# 2. pass this condition into the dataFrame
df_can[condition]

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
8,Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,224,218,198,205,267,252,236,258,207,3310
11,Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,359,236,203,125,165,209,138,161,57,2649
13,Bahrain,Asia,Western Asia,Developing regions,0,2,1,1,1,3,...,12,12,22,9,35,28,21,39,32,475
14,Bangladesh,Asia,Southern Asia,Developing regions,83,84,86,81,98,92,...,4171,4014,2897,2939,2104,4721,2694,2640,3789,65568
20,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,...,5,10,7,36,865,1464,1879,1075,487,5876
25,Brunei Darussalam,Asia,South-Eastern Asia,Developing regions,79,6,8,2,2,4,...,4,5,11,10,5,12,6,3,6,600
30,Cambodia,Asia,South-Eastern Asia,Developing regions,12,19,26,33,10,7,...,370,529,460,354,203,200,196,233,288,6538
36,China,Asia,Eastern Asia,Developing regions,5123,6682,3308,1863,1527,1816,...,42584,33518,27642,30037,29622,30391,28502,33024,34129,659962
37,"China, Hong Kong Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,729,712,674,897,657,623,591,728,774,9327
38,"China, Macao Special Administrative Region",Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,21,32,16,12,21,21,13,33,29,284
46,Cyprus,Asia,Western Asia,Developing regions,132,128,84,46,46,43,...,7,9,4,7,6,18,6,12,16,1126
48,Democratic People's Republic of Korea,Asia,Eastern Asia,Developing regions,1,1,3,1,4,3,...,14,10,7,19,11,45,97,66,17,388
66,Georgia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,114,125,132,112,128,126,139,147,125,2068
79,India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,...,36210,33848,28742,28261,29456,34235,27509,30933,33087,691904
80,Indonesia,Asia,South-Eastern Asia,Developing regions,186,178,252,115,123,100,...,632,613,657,661,504,712,390,395,387,13150
81,Iran (Islamic Republic of),Asia,Southern Asia,Developing regions,1172,1429,1822,1592,1977,1648,...,5837,7480,6974,6475,6580,7477,7479,7534,11291,175923
82,Iraq,Asia,Western Asia,Developing regions,262,245,260,380,428,231,...,2226,1788,2406,3543,5450,5941,6196,4041,4918,69789
84,Israel,Asia,Western Asia,Developing regions,1403,1711,1334,541,446,680,...,2446,2625,2401,2562,2316,2755,1970,2134,1945,66508
87,Japan,Asia,Eastern Asia,Developed regions,701,756,598,309,246,198,...,1067,1212,1250,1284,1194,1168,1265,1214,982,27707
88,Jordan,Asia,Western Asia,Developing regions,177,160,155,113,102,179,...,1940,1827,1421,1581,1235,1831,1635,1206,1255,35406
89,Kazakhstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,506,408,436,394,431,377,381,462,348,8490
92,Kuwait,Asia,Western Asia,Developing regions,1,0,8,2,1,4,...,66,35,62,53,68,67,58,73,48,2025
93,Kyrgyzstan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,173,161,135,168,173,157,159,278,123,2353
94,Lao People's Democratic Republic,Asia,South-Eastern Asia,Developing regions,11,6,16,16,7,17,...,42,74,53,32,39,54,22,25,15,1089
96,Lebanon,Asia,Western Asia,Developing regions,1409,1119,1159,789,1253,1683,...,3709,3802,3467,3566,3077,3432,3072,1614,2172,115359
105,Malaysia,Asia,South-Eastern Asia,Developing regions,786,816,813,448,384,374,...,593,580,600,658,640,802,409,358,204,24417
106,Maldives,Asia,Southern Asia,Developing regions,0,0,0,1,0,0,...,0,0,2,1,7,4,3,1,1,30
114,Mongolia,Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,59,64,82,59,118,169,103,68,99,952
118,Myanmar,Asia,South-Eastern Asia,Developing regions,80,62,46,31,41,23,...,210,953,1887,975,1153,556,368,193,262,9245
121,Nepal,Asia,Southern Asia,Developing regions,1,1,6,1,2,4,...,607,540,511,581,561,1392,1129,1185,1308,10222
129,Oman,Asia,Western Asia,Developing regions,0,0,0,8,0,0,...,14,18,16,10,7,14,10,13,11,224
130,Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,...,14314,13127,10124,8994,7217,6811,7468,11227,12603,241600
136,Philippines,Asia,South-Eastern Asia,Developing regions,6051,5921,5249,4562,3801,3150,...,18139,18400,19837,24887,28573,38617,36765,34315,29544,511391
139,Qatar,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,11,2,5,9,6,18,3,14,6,157
140,Republic of Korea,Asia,Eastern Asia,Developing regions,1011,1456,1572,1081,847,962,...,5832,6215,5920,7294,5874,5537,4588,5316,4509,142581
151,Saudi Arabia,Asia,Western Asia,Developing regions,0,0,1,4,1,2,...,198,252,188,249,246,330,278,286,267,3425
156,Singapore,Asia,South-Eastern Asia,Developing regions,241,301,337,169,128,139,...,392,298,690,734,366,805,219,146,141,14579
162,Sri Lanka,Asia,Southern Asia,Developing regions,185,371,290,197,1086,845,...,4930,4714,4123,4756,4547,4422,3309,3338,2394,148358
163,State of Palestine,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,453,627,441,481,400,654,555,533,462,6512
169,Syrian Arab Republic,Asia,Western Asia,Developing regions,315,419,409,269,264,385,...,1458,1145,1056,919,917,1039,1005,650,1009,31485
170,Tajikistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,85,46,44,15,50,52,47,34,39,503
171,Thailand,Asia,South-Eastern Asia,Developing regions,56,53,113,65,82,66,...,575,500,487,519,512,499,396,296,400,9174
177,Turkey,Asia,Western Asia,Developing regions,481,874,706,280,338,202,...,2065,1638,1463,1122,1238,1492,1257,1068,729,31781
178,Turkmenistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,40,26,37,13,20,30,20,20,14,310
182,United Arab Emirates,Asia,Western Asia,Developing regions,0,2,2,1,2,0,...,31,42,37,33,37,86,60,54,46,836
187,Uzbekistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,330,262,284,215,288,289,162,235,167,3368
190,Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
192,Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,...,161,140,122,133,128,211,160,174,217,2985

In [32]:
df_can[(df_can['Continent']=='Africa')&(df_can['Region']=='Southern Africa')]

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
23,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,...,7,11,8,28,15,42,53,64,76,396
97,Lesotho,Africa,Southern Africa,Developing regions,1,1,1,2,7,5,...,4,0,4,1,8,7,1,0,6,107
119,Namibia,Africa,Southern Africa,Developing regions,0,5,5,3,2,1,...,6,19,13,26,14,16,23,24,83,320
160,South Africa,Africa,Southern Africa,Developing regions,1026,1118,781,379,271,310,...,988,1111,1200,1123,1188,1238,959,1243,1240,40568
166,Swaziland,Africa,Southern Africa,Developing regions,4,1,1,0,10,7,...,7,7,5,6,10,3,13,17,39,188

In [33]:
df_can.sort_values(by='Total', ascending=False, axis=0, inplace=True)
top_5 = df_can.head(5)
top_5

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
79,India,Asia,Southern Asia,Developing regions,8880,8670,8147,7338,5704,4211,...,36210,33848,28742,28261,29456,34235,27509,30933,33087,691904
36,China,Asia,Eastern Asia,Developing regions,5123,6682,3308,1863,1527,1816,...,42584,33518,27642,30037,29622,30391,28502,33024,34129,659962
183,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,Developed regions,22045,24796,20620,10015,10170,9564,...,7258,7140,8216,8979,8876,8724,6204,6195,5827,551500
136,Philippines,Asia,South-Eastern Asia,Developing regions,6051,5921,5249,4562,3801,3150,...,18139,18400,19837,24887,28573,38617,36765,34315,29544,511391
130,Pakistan,Asia,Southern Asia,Developing regions,978,972,1201,900,668,514,...,14314,13127,10124,8994,7217,6811,7468,11227,12603,241600

In [35]:
 df_can.sort_values(by='2010', ascending=False, axis=0, inplace=True)
 top3_2010 = df_can['2010'].head(3)
 top3_2010

136    38617
79     34235
36     30391
Name: 2010, dtype: int64